### ISSUE TITLE
module manquants dans le connexion.py

### ISSUE THREAD

**Issue by t0piCyb** [gregoirebezier/chatgpt_selenium#1]
après avoir réalisé toutes les commandes d'installation du readme on obtient cette erreur: 
python3 chatgpt_automatisation.py 
Traceback (most recent call last):
  File "~/chatgpt_selenium/chatgpt_automatisation.py", line 7, in <module>
    from connexion import connexion
  File "~/chatgpt_selenium/connexion.py", line 5, in <module>
    from webdriver_manager.chrome import ChromeDriverManager
ModuleNotFoundError: No module named 'webdriver_manager'

Je suppose qu'il faut ajouter qq fichiers

**Comment by gregoirebezier** [comment]
pip install webdriver-manager==4.0.1

Merci ! Je vais l'ajouter au requirements.txt
